<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:This is the layer in which we have access to our data. It takes the data and passes it to the hidden layer(s) for calculations that are meant to be preformed on our data

### Hidden Layer: This is the calculation layer, we have no access to our data in the layer. Once the calculations are done hidden layer would pass the final results to the output layer. We cannot access the hidden layer unless through the input layer and we cannot interact with the functions perfomed in this layer. 

### Output Layer: This is the layer which turns out the results to in a form of vector. Activation function could be used here to convert the output to the format we require. 

### Neuron:neurons are elementary units that take an input and preform functions on them and them pass them as an output

### Weight:Weight in neural networks are the importance or probability of one outcome affecting the other outcome.

### Activation Function: Activation function works a gate keeper between layers in a sense that each node has an activation function and activation function decides how much signal needs to be passed to the next layer

### Node Map: Node map is a visual architecture of the nueral network, and it works like a flow chart. 

### Perceptron: Perceptrion is the simplest form of neural network consisting of one node. Perceptron takes multiple inputs, sums them together by their weigt and passes it out as one output. 


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

### Inout takes the data and passes it to the hidden layer through multiple neurons, in the hidden layer each neuron is multiplied by its weight and added to the bias through actication functions this would help our model to find the best way to find the best results. At the end the best out put(s) are passed as results to the output layer

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [2]:
##### Your Code Here #####
import numpy as np

# Set inputs and correct outputs 
inputs = np.array([
    [0,0],
    [1,0],
    [0,1],
    [1,1]
])

correct_outputs = [[1],[1],[1],[0]]

# Sigmoid activation function and its derivative for updating weights
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx=sigmoid(x)
    return sx*(1-sx)

In [3]:
# initializing random weights and updating weights with sigmoid

# Random Weights
weights = 2 * np.random.random((2,1)) -1
weights

array([[0.94664756],
       [0.29429191]])

In [4]:
# Sum of weighted inputs 

weighted_sum = np.dot(inputs, weights)
weighted_sum

array([[0.        ],
       [0.94664756],
       [0.29429191],
       [1.24093948]])

In [5]:
# Multiply sigmoid activation functiion by weighted sum
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.5       ],
       [0.72044048],
       [0.57304654],
       [0.7757275 ]])

In [6]:
# Calculate error
error = correct_outputs - activated_output
error

array([[ 0.5       ],
       [ 0.27955952],
       [ 0.42695346],
       [-0.7757275 ]])

In [7]:
#Gradient Descent (***Ask Jeff about this)
adjustments = error * sigmoid_derivative(weighted_sum)
adjustments

array([[ 0.125     ],
       [ 0.05630496],
       [ 0.10446023],
       [-0.13495668]])

In [8]:
weights += np.dot(inputs.T, adjustments)
weights

array([[0.86799584],
       [0.26379546]])

In [10]:
# Put them all together and iterate 10000 times with weights

# Updating weights 10,000 times

for iteration in range(10000):
    weighted_sum = np.dot(inputs, weights)
    activated_output = sigmoid(weighted_sum)
    error = correct_outputs - activated_output
    adjustments = error * sigmoid_derivative(weighted_sum)
    
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[ 1.52655666e-16]
 [-3.05311332e-16]]
Output after training
[[0.5]
 [0.5]
 [0.5]
 [0.5]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [4]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [10]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = ...

In [ ]:
##### Update this Class #####

class Perceptron:
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return None
    
    def __sigmoid_derivative(self, x):
        return None

    def fit(self, X, y):
    """Fit training data
    X : Training vectors, X.shape : [#samples, #features]
    y : Target values, y.shape : [#samples]
    """

        # Randomly Initialize Weights
        weights = ...

        for i in range(self.niter):
            # Weighted sum of inputs / weights

            # Activate!

            # Cac error

            # Update the Weights


    def predict(self, X):
    """Return class label after unit step"""
        return None

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?